# Generated by Django 5.0.4 on 2024-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default='1000-01-01', verbose_name='дата производства продукта'),
        ),
    ]
